// Pool de ataques por nivel y tipo + verificación de aprendizaje al subir nivel.
// Sin dependencias externas.

// === POOL DE ATAQUES POR NIVEL Y TIPO ===

const LEARN_POOL = {
  fire: [
    {
      lv: 3,
      mv: {
        nm: 'Nitrocarga',
        tp: 'fire',
        pw: 50,
        pp: 20,
        mp: 20,
        acc: 100,
        ef: 'spdUp',
        desc: 'Embiste envuelto en llamas. Sube tu velocidad +1.',
      },
    },
    {
      lv: 6,
      mv: {
        nm: 'Lluvia Ígnea',
        tp: 'fire',
        pw: 50,
        pp: 15,
        mp: 15,
        acc: 95,
        ef: 'burn20',
        desc: 'Lluvia de brasas ardientes. 20% de quemar al rival.',
      },
    },
    {
      lv: 9,
      mv: {
        nm: 'Pantalla Humo',
        tp: 'fire',
        pw: 0,
        pp: 10,
        mp: 10,
        acc: 100,
        ef: 'accDn',
        desc: 'Crea una cortina de humo. Baja precisión del rival.',
      },
    },
    {
      lv: 12,
      mv: {
        nm: 'Voluntad Ardiente',
        tp: 'fire',
        pw: 0,
        pp: 10,
        mp: 10,
        acc: 100,
        ef: 'atkSpdUpDefDn',
        desc: 'Enciende tu espíritu. ATK y SPD +1, pero DEF -1.',
      },
    },
    {
      lv: 15,
      mv: {
        nm: 'Golpe Volcán',
        tp: 'fire',
        pw: 75,
        pp: 10,
        mp: 10,
        acc: 90,
        ef: 'selfDefDn',
        desc: 'Golpe con furia volcánica. Baja tu propia defensa -1.',
      },
    },
    {
      lv: 18,
      mv: {
        nm: 'Día Soleado',
        tp: 'fire',
        pw: 0,
        pp: 5,
        mp: 5,
        acc: 100,
        ef: 'sunUp',
        desc: 'Intensifica el sol por 5 turnos. Fuego +50%, Agua -50%.',
      },
    },
    {
      lv: 21,
      mv: {
        nm: 'Explosión Solar',
        tp: 'fire',
        pw: 90,
        pp: 5,
        mp: 5,
        acc: 85,
        ef: 'charge',
        desc: 'Concentra energía solar y explota. Muy potente pero imprecisa.',
      },
    },
    {
      lv: 24,
      mv: {
        nm: 'Danza Espada',
        tp: 'normal',
        pw: 0,
        pp: 15,
        mp: 15,
        acc: 100,
        ef: 'atkUp2',
        desc: 'Danza guerrera. Sube ATK +2.',
      },
    },
  ],
  water: [
    {
      lv: 3,
      mv: {
        nm: 'Rayo Burbuja',
        tp: 'water',
        pw: 45,
        pp: 20,
        mp: 20,
        acc: 100,
        ef: 'spdDn30',
        desc: 'Burbujas que explotan. 30% de bajar SPD rival.',
      },
    },
    {
      lv: 6,
      mv: {
        nm: 'Aqua Jet',
        tp: 'water',
        pw: 40,
        pp: 20,
        mp: 20,
        acc: 100,
        ef: 'priority',
        desc: 'Ataque rápido de agua. Siempre golpea primero.',
      },
    },
    {
      lv: 9,
      mv: {
        nm: 'Refugio',
        tp: 'water',
        pw: 0,
        pp: 10,
        mp: 10,
        acc: 100,
        ef: 'defUp2',
        desc: 'Se refugia en su caparazón. DEF sube +2.',
      },
    },
    {
      lv: 12,
      mv: {
        nm: 'Cascada',
        tp: 'water',
        pw: 65,
        pp: 15,
        mp: 15,
        acc: 95,
        ef: 'flinch20',
        desc: 'Cae agua como cascada. 20% de hacer retroceder.',
      },
    },
    {
      lv: 15,
      mv: {
        nm: 'Danza Lluvia',
        tp: 'water',
        pw: 0,
        pp: 5,
        mp: 5,
        acc: 100,
        ef: 'rainUp',
        desc: 'Invoca lluvia por 5 turnos. Agua +50%, Fuego -50%.',
      },
    },
    {
      lv: 18,
      mv: {
        nm: 'Torbellino',
        tp: 'water',
        pw: 55,
        pp: 10,
        mp: 10,
        acc: 90,
        ef: 'trap2',
        desc: 'Atrapa al rival en un remolino por 2 turnos.',
      },
    },
    {
      lv: 21,
      mv: {
        nm: 'Niebla',
        tp: 'water',
        pw: 0,
        pp: 10,
        mp: 10,
        acc: 100,
        ef: 'accDnBoth',
        desc: 'Cubre el campo de niebla. Baja precisión de ambos.',
      },
    },
    {
      lv: 24,
      mv: {
        nm: 'Agilidad',
        tp: 'normal',
        pw: 0,
        pp: 15,
        mp: 15,
        acc: 100,
        ef: 'spdUp2',
        desc: 'Relaja los músculos. Sube SPD +2.',
      },
    },
  ],
  plant: [
    {
      lv: 3,
      mv: {
        nm: 'Látigo Cepa',
        tp: 'plant',
        pw: 55,
        pp: 15,
        mp: 15,
        acc: 100,
        ef: 'defDn',
        desc: 'Azota con lianas. Baja DEF del rival -1.',
      },
    },
    {
      lv: 6,
      mv: {
        nm: 'Bomba Semilla',
        tp: 'plant',
        pw: 60,
        pp: 20,
        mp: 20,
        acc: 100,
        desc: 'Lanza semillas explosivas. Daño sólido y preciso.',
      },
    },
    {
      lv: 9,
      mv: {
        nm: 'Drenadoras',
        tp: 'plant',
        pw: 0,
        pp: 10,
        mp: 10,
        acc: 100,
        ef: 'leech4',
        desc: 'Planta semillas drenadoras por 4 turnos. Roba HP cada turno.',
      },
    },
    {
      lv: 12,
      mv: {
        nm: 'Hoja Navaja',
        tp: 'plant',
        pw: 50,
        pp: 15,
        mp: 15,
        acc: 100,
        ef: 'highCrit',
        desc: 'Corte preciso con hoja. Alta probabilidad de crítico.',
      },
    },
    {
      lv: 15,
      mv: {
        nm: 'Crecimiento',
        tp: 'plant',
        pw: 0,
        pp: 20,
        mp: 20,
        acc: 100,
        ef: 'atkDefUp',
        desc: 'Absorbe nutrientes. ATK y DEF suben +1.',
      },
    },
    {
      lv: 18,
      mv: {
        nm: 'Gigadrenado',
        tp: 'plant',
        pw: 55,
        pp: 10,
        mp: 10,
        acc: 100,
        ef: 'drain50',
        desc: 'Drena energía vital. Recupera 50% del daño causado.',
      },
    },
    {
      lv: 21,
      mv: {
        nm: 'Espora Sueño',
        tp: 'plant',
        pw: 0,
        pp: 10,
        mp: 10,
        acc: 75,
        ef: 'sleep2',
        desc: 'Lanza esporas somníferas. Duerme al rival 2 turnos. Imprecisa.',
      },
    },
    {
      lv: 24,
      mv: {
        nm: 'Campo de Flores',
        tp: 'plant',
        pw: 0,
        pp: 5,
        mp: 5,
        acc: 100,
        ef: 'healField3',
        desc: 'Crea un campo floral por 3 turnos. Cura HP cada turno.',
      },
    },
  ],
  dragon: [
    {
      lv: 3,
      mv: {
        nm: 'Garra Umbría',
        tp: 'dragon',
        pw: 60,
        pp: 15,
        mp: 15,
        acc: 95,
        ef: 'flinch15',
        desc: 'Zarpazo oscuro. 15% de hacer retroceder al rival.',
      },
    },
    {
      lv: 6,
      mv: {
        nm: 'Furia Dragón',
        tp: 'dragon',
        pw: 40,
        pp: 10,
        mp: 10,
        acc: 100,
        ef: 'fixedDmg',
        desc: 'Rabia pura. Siempre hace exactamente 40 de daño fijo.',
      },
    },
    {
      lv: 9,
      mv: {
        nm: 'Escama Protectora',
        tp: 'dragon',
        pw: 0,
        pp: 10,
        mp: 10,
        acc: 100,
        ef: 'shield1',
        desc: 'Se cubre con escamas. El próximo ataque recibido hace -50% daño.',
      },
    },
    {
      lv: 12,
      mv: {
        nm: 'Pulso Dragón',
        tp: 'dragon',
        pw: 65,
        pp: 10,
        mp: 10,
        acc: 100,
        ef: 'neverMiss',
        desc: 'Pulso de energía dracónica. Nunca falla.',
      },
    },
    {
      lv: 15,
      mv: {
        nm: 'Danza Dragón',
        tp: 'dragon',
        pw: 0,
        pp: 10,
        mp: 10,
        acc: 100,
        ef: 'atkSpdUp',
        desc: 'Danza ancestral. ATK y SPD suben +1.',
      },
    },
    {
      lv: 18,
      mv: {
        nm: 'Cola Férrea',
        tp: 'dragon',
        pw: 70,
        pp: 10,
        mp: 10,
        acc: 90,
        ef: 'selfSpdDn',
        desc: 'Coletazo de hierro. Potente pero baja tu SPD -1.',
      },
    },
    {
      lv: 21,
      mv: {
        nm: 'Mirada Dragón',
        tp: 'dragon',
        pw: 0,
        pp: 10,
        mp: 10,
        acc: 100,
        ef: 'atkDn2',
        desc: 'Mirada intimidante. Baja ATK del rival -2.',
      },
    },
    {
      lv: 24,
      mv: {
        nm: 'Danza Espada',
        tp: 'normal',
        pw: 0,
        pp: 15,
        mp: 15,
        acc: 100,
        ef: 'atkUp2',
        desc: 'Danza guerrera. Sube ATK +2.',
      },
    },
  ],
  fairy: [
    {
      lv: 3,
      mv: {
        nm: 'Dulce Aroma',
        tp: 'fairy',
        pw: 45,
        pp: 20,
        mp: 20,
        acc: 100,
        ef: 'atkDn30',
        desc: 'Aroma dulce que relaja. 30% de bajar ATK rival.',
      },
    },
    {
      lv: 6,
      mv: {
        nm: 'Beso Drenaje',
        tp: 'fairy',
        pw: 50,
        pp: 15,
        mp: 15,
        acc: 100,
        ef: 'drain25',
        desc: 'Beso que roba energía. Recupera 25% del daño causado.',
      },
    },
    {
      lv: 9,
      mv: {
        nm: 'Deseo',
        tp: 'fairy',
        pw: 0,
        pp: 10,
        mp: 10,
        acc: 100,
        ef: 'wishHeal',
        desc: 'Pide un deseo. Al turno siguiente recupera 50% de HP máximo.',
      },
    },
    {
      lv: 12,
      mv: {
        nm: 'Voz Cautivadora',
        tp: 'fairy',
        pw: 55,
        pp: 15,
        mp: 15,
        acc: 95,
        ef: 'confuse20',
        desc: 'Canto hipnótico. 20% de confundir al rival.',
      },
    },
    {
      lv: 15,
      mv: {
        nm: 'Encanto Total',
        tp: 'fairy',
        pw: 0,
        pp: 10,
        mp: 10,
        acc: 100,
        ef: 'atkDn2',
        desc: 'Encanto irresistible. Baja ATK del rival -2.',
      },
    },
    {
      lv: 18,
      mv: {
        nm: 'Fuerza Lunar',
        tp: 'fairy',
        pw: 70,
        pp: 10,
        mp: 10,
        acc: 90,
        ef: 'atkDn',
        desc: 'Poder de la luna llena. Baja ATK del rival -1.',
      },
    },
    {
      lv: 21,
      mv: {
        nm: 'Campo Mágico',
        tp: 'fairy',
        pw: 0,
        pp: 5,
        mp: 5,
        acc: 100,
        ef: 'fairyUp',
        desc: 'Crea campo mágico por 5 turnos. Hada +50%.',
      },
    },
    {
      lv: 24,
      mv: {
        nm: 'Neblina Feérica',
        tp: 'fairy',
        pw: 0,
        pp: 10,
        mp: 10,
        acc: 100,
        ef: 'clearStatus',
        desc: 'Neblina curativa. Elimina todos los estados alterados propios.',
      },
    },
  ],
  normal: [
    {
      lv: 3,
      mv: {
        nm: 'Velocidad Extrema',
        tp: 'normal',
        pw: 60,
        pp: 10,
        mp: 10,
        acc: 100,
        ef: 'priority',
        desc: 'Ataque a velocidad extrema. Siempre golpea primero.',
      },
    },
    {
      lv: 6,
      mv: {
        nm: 'Golpe Cuerpo',
        tp: 'normal',
        pw: 70,
        pp: 15,
        mp: 15,
        acc: 95,
        ef: 'paralyze20',
        desc: 'Golpe con todo el cuerpo. 20% de paralizar.',
      },
    },
    {
      lv: 9,
      mv: {
        nm: 'Protección',
        tp: 'normal',
        pw: 0,
        pp: 10,
        mp: 10,
        acc: 100,
        ef: 'protect',
        desc: 'Se protege completamente. Bloquea el próximo ataque.',
      },
    },
    {
      lv: 12,
      mv: {
        nm: 'Doble Golpe',
        tp: 'normal',
        pw: 30,
        pp: 15,
        mp: 15,
        acc: 90,
        ef: 'hitTwice',
        desc: 'Golpea dos veces seguidas. Daño x2.',
      },
    },
    {
      lv: 15,
      mv: {
        nm: 'Venganza',
        tp: 'normal',
        pw: 60,
        pp: 10,
        mp: 10,
        acc: 100,
        ef: 'revenge',
        desc: 'Si recibiste daño este turno, el poder se duplica.',
      },
    },
    {
      lv: 18,
      mv: {
        nm: 'Inversión',
        tp: 'normal',
        pw: 0,
        pp: 10,
        mp: 10,
        acc: 100,
        ef: 'reversal',
        desc: 'Contraataque desesperado. Más daño cuanto menos HP tengas.',
      },
    },
    {
      lv: 21,
      mv: {
        nm: 'Espejo',
        tp: 'normal',
        pw: 0,
        pp: 10,
        mp: 10,
        acc: 100,
        ef: 'mirror',
        desc: 'Refleja el último ataque recibido.',
      },
    },
    {
      lv: 24,
      mv: {
        nm: 'Maldición',
        tp: 'normal',
        pw: 0,
        pp: 5,
        mp: 5,
        acc: 100,
        ef: 'curse',
        desc: 'Sacrifica 50% de tu HP para maldecir al rival. Pierde 12% HP/turno.',
      },
    },
  ],
};

// === VERIFICAR SI APRENDE ATAQUE AL SUBIR DE NIVEL ===
function checkLearnMove(cre) {
  const pool = LEARN_POOL[cre.tp];
  if (!pool) return null;
  const learn = pool.find((l) => l.lv === cre.lv);
  if (!learn) return null;
  if (cre.mv.some((m) => m.nm === learn.mv.nm)) return null;
  return { ...learn.mv, pp: learn.mv.mp };
}

export { LEARN_POOL, checkLearnMove };
